--------------------------------------------------------
--  File created - Tuesday-June-14-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEPLOYMENT_MANIFEST_ITEMS
--------------------------------------------------------

  CREATE TABLE "RELAUT"."DEPLOYMENT_MANIFEST_ITEMS" 
   (	"COMMENTS" VARCHAR2(250 BYTE), 
	"ITEM_ID" NUMBER, 
	"DEPLOYMENT_ID" NUMBER, 
	"PROJECT_ID" NUMBER, 
	"DEPLOYMENT_ORDER" NUMBER, 
	"NOTES" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPLOYMENT_MANIFEST_ITEMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RELAUT"."DEPLOYMENT_MANIFEST_ITEMS_PK" ON "RELAUT"."DEPLOYMENT_MANIFEST_ITEMS" ("ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DEPLOYMENT_MANIFEST_ITEMS
--------------------------------------------------------

  ALTER TABLE "RELAUT"."DEPLOYMENT_MANIFEST_ITEMS" ADD CONSTRAINT "DEPLOYMENT_MANIFEST_ITEMS_PK" PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RELAUT"."DEPLOYMENT_MANIFEST_ITEMS" MODIFY ("ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DEPLOYMENT_MANIFEST_ITEMS
--------------------------------------------------------

  ALTER TABLE "RELAUT"."DEPLOYMENT_MANIFEST_ITEMS" ADD CONSTRAINT "DEPLOYMENT_MANIFEST_ITEMS_FK1" FOREIGN KEY ("DEPLOYMENT_ID")
	  REFERENCES "RELAUT"."DEPLOYMENT_MANIFEST_HEADER" ("DEPLOYMENT_ID") ENABLE;
  ALTER TABLE "RELAUT"."DEPLOYMENT_MANIFEST_ITEMS" ADD CONSTRAINT "DEPLOYMENT_MANIFEST_ITEMS_FK2" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "RELAUT"."PROJECT" ("PROJECT_ID") ENABLE;
